name: Build and Deploy code

on: [push, pull_request]

jobs:
  job1:
    env:
      DATABASE_HOSTNAME: ${{secrets.DATABASE_HOSTNAME}}
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: root
      DATABASE_NAME: FastAPI
      DATABASE_USERNAME: postgres
      SECRET_KEY: uhfdsuihafiudshiufahdkjhfjakhsdiufhuasdhfijhasdjifhkjashdjhfuieuruiyewjkah8327737
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    runs-on: ubuntu-lastest
    steps:
      - name: Pulling git repo
        uses: actions/checkout@v4
      - name: Install python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' 
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install all dependencies
        run: pip install -r requirements.txt
      - name: test with pytest
        run: |
          pip install pytest
          pytest
      
