name: Build and Deploy code

on: [push, pull_request]

jobs:
  job1:
    runs-on: ubuntu-lastest
    steps:
      - name: Pulling git repo
        uses: actions/checkout@v2
      - name: Say hi to user
        run: echo "Hello world"
